import type { CustomerCreateForm } from "@/schemas/customer";

export const cadastroDefaultValues: CustomerCreateForm = {
  name: "",
  lastName: "",
  birthDate: "",
  motherName: "",
  fatherName: "",
  email: "",
  password: "",
  cellPhoneNumber: "",
  monthlyIncome: "",
  documents: {
    rgDocument: "",
    securityNumber: "",
    issuingInstitution: "",
    uf: "",
  },
  address: {
    cep: "",
    neighborhood: "",
    residenceNumber: "",
    city: "",
    uf: "",
    publicPlace: "",
    addtionalInformation: "",
  },
};

export const cadastroUfOptions = [
  { value: "AC", label: "AC - Acre" },
  { value: "AL", label: "AL - Alagoas" },
  { value: "AP", label: "AP - Amapa" },
  { value: "AM", label: "AM - Amazonas" },
  { value: "BA", label: "BA - Bahia" },
  { value: "CE", label: "CE - Ceara" },
  { value: "DF", label: "DF - Distrito Federal" },
  { value: "ES", label: "ES - Espirito Santo" },
  { value: "GO", label: "GO - Goias" },
  { value: "MA", label: "MA - Maranhao" },
  { value: "MT", label: "MT - Mato Grosso" },
  { value: "MS", label: "MS - Mato Grosso do Sul" },
  { value: "MG", label: "MG - Minas Gerais" },
  { value: "PA", label: "PA - Para" },
  { value: "PB", label: "PB - Paraiba" },
  { value: "PR", label: "PR - Parana" },
  { value: "PE", label: "PE - Pernambuco" },
  { value: "PI", label: "PI - Piaui" },
  { value: "RJ", label: "RJ - Rio de Janeiro" },
  { value: "RN", label: "RN - Rio Grande do Norte" },
  { value: "RS", label: "RS - Rio Grande do Sul" },
  { value: "RO", label: "RO - Rondonia" },
  { value: "RR", label: "RR - Roraima" },
  { value: "SC", label: "SC - Santa Catarina" },
  { value: "SP", label: "SP - Sao Paulo" },
  { value: "SE", label: "SE - Sergipe" },
  { value: "TO", label: "TO - Tocantins" },
] as const;